version: '3.0'

services:

  nginx:
    image: nginx
    depends_on:
      - php
    volumes:
      - ./default.nginx:/etc/nginx/conf.d/default.conf
      - ./project/:/var/www/html/
      - ./log/nginx/:/var/log/nginx/
    networks:
      - frontend
      - backend
    labels:
      - "traefik.port=80"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:erp.mycentra.local"
    ports:
        - '88:80'  
    links: 
      - php

  symfony:
    build:
      context: ./docker/symfony
    depends_on:
      - php
    volumes:
      - ./project/:/home/symfony/
    networks:
      - backend
      - frontend
    tty: true
    labels:
      - "traefik.enable=false"
    links:
      - mysql  

  php:
    build:
      context: ./docker/php
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./project/:/var/www/html/
    networks:
      - backend
    labels:
      - "traefik.enable=false"
    links:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'centraservices'
      MYSQL_USER: 'centraservices'
      MYSQL_PASSWORD: '123321'
      MYSQL_ROOT_PASSWORD: '123321'
    ports:
      - '3307:3306'    
    volumes:
      - ./mysql/:/var/lib/mysql  
    networks:
      - backend
      - frontend
    labels:
      - "traefik.enable=true"

  yarn:
    build:
      context: ./docker/yarn
    volumes:
      - ./project/:/home/yarn/
    networks:
      - backend
    labels:
      - "traefik.enable=false"
    tty: true

  redis:
    image: redis
    ports:
      - '6379:6379'    
    volumes:
      - ./redis/:/data
    networks:
      - backend
      - frontend
    tty: true
    labels:
      - "traefik.enable=true"

networks:
  frontend:
      external: 
          name: proxy
  backend:
      external: false

